#!/bin/bash

echo "$@"|grep -- "--brief" &>/dev/null
is_brief=$?

if [ $is_brief -eq 0 ]; then
    cat <<EOF
ARRAY metadata=imsm UUID=e0fb362e:9865d1c0:cdb0f5e3:27c9a085
ARRAY /dev/md/Volume0 container=e0fb362e:9865d1c0:cdb0f5e3:27c9a085 member=0 UUID=1d1335e9:79d4be6a:e16b7fa7:fe8c41f6
EOF
else
    cat <<EOF
MD_METADATA=imsm
MD_LEVEL=container
MD_UUID=e0fb362e:9865d1c0:cdb0f5e3:27c9a085
MD_DEVICES=2
EOF
fi
