# This is a simple ansible playbook for installing packages needed by the
# libblockdev test suite.
# You can do this by using 'make install-requires' or manually using
# 'ansible-playbook -K -i "localhost," -c local install-test-dependencies.yml'
# Currently only Fedora, CentOS and Debian/Ubuntu are supported by this playbook.

---
- hosts: all
  become: true
  vars:
    test_dependencies: true  # whether to install test dependencies or not

  tasks:
  - name: Include tasks from libblockdev-tasks.yml
    ansible.builtin.include_tasks: libblockdev-tasks.yml
